deployKF/website

mkdocs.yml
=> chore: change feedback icons

content/reference/.pages, content/reference/deploykf-values.md, content/reference/tools.md, content/releases/version-matrix.md
=> docs: page cleanup

README.md
=> chore: update local dev readme

content/guides/install-deploykf-cli.md
closes https://github.com/deployKF/cli/issues/10
=> docs: fix cli cpu architecture check

mkdocs.yml
=> docs: update social card color

content/.pages, content/index.md
=> docs: update homepage title

content/about/kubeflow-vs-deploykf.md, content/guides/getting-started.md, content/guides/migrate-from-kubeflow-manifests.md, content/reference/tools.md, content/releases/changelog-deploykf-cli.md, content/releases/changelog-deploykf.md
=> docs: update getting started

content/about/support.md, content/faq.md, content/guides/getting-started.md
=> docs: update partner email

overrides/sitemap.xml
=> chore: fix sitemap lastmod times

README.md, content/guides/deploykf-cli.md, content/guides/local-quickstart.md, content/releases/version-matrix--deploykf-dependencies.csv
=> docs: update version matrix

content/guides/getting-started.md, content/guides/local-quickstart.md
=> docs: add github star callout

content/faq.md, content/guides/getting-started.md, content/guides/local-quickstart.md, content/guides/platform/deploykf-gateway.md, content/guides/tools/external-mysql.md, content/guides/tools/external-object-store.md
=> docs: update config guides

content/guides/tools/external-mysql.md, content/guides/tools/external-object-store.md
=> docs: update s3 guide

content/about/community.md, content/about/support.md, content/assets/stylesheets/admonitions.css, content/faq.md, content/guides/getting-started.md, content/guides/local-quickstart.md, content/guides/platform/deploykf-authentication.md, content/guides/platform/deploykf-dashboard.md, content/guides/platform/deploykf-gateway.md, content/guides/platform/deploykf-profiles.md, content/guides/tools/external-mysql.md, content/guides/tools/external-object-store.md, content/user-guides/access-kubeflow-pipelines-api.md, content/user-guides/gitops-for-kubeflow-pipelines.md, macros/custom_macros.py
=> docs: update guides

content/user-guides/access-kubeflow-pipelines-api.md
=> docs: add KFP SDK version warning

content/assets/stylesheets/color.css, content/assets/stylesheets/overrides.css, content/guides/.pages, content/reference/.pages, content/reference/future-tools.md, content/reference/tools.md, content/releases/.pages, mkdocs.yml, overrides/partials/nav-item.html
=> chore: visual separation between nav sections

content/guides/getting-started.md, content/guides/platform/deploykf-profiles.md, content/user-guides/access-kubeflow-pipelines-api.md
There is an issue where the `verify` parameter of the `requests.Session()` is ignored if `REQUESTS_CA_BUNDLE`or `CURL_CA_BUNDLE` env-vars are set, so we update the example script to explicitly pass `verify` with each request.
=> docs: update KFP dex script to fix SSL issue

content/assets/stylesheets/overrides.css, content/reference/deploykf-values.md
=> chore: improve values page formatting

content/assets/stylesheets/home.css, overrides/home.html
=> chore: improve home styles

content/assets/stylesheets/home.css, content/assets/stylesheets/overrides.css, content/faq.md, content/guides/getting-started.md, content/guides/local-quickstart.md, mkdocs.yml, overrides/home.html
=> chore: update introduction and homepage

content/assets/stylesheets/home.css
=> chore: fix homepage mobile styles

content/about/community.md, content/about/kubeflow-vs-deploykf.md, content/about/support.md, content/guides/platform/deploykf-authentication.md, content/guides/platform/deploykf-profiles.md, mkdocs.yml
=> docs: update authentication guide

content/guides/platform/deploykf-authentication.md
=> docs: small changes to auth guide

content/about/introduction.md, content/faq.md, content/guides/getting-started.md, content/guides/kubeflow-distributions.md, content/guides/local-quickstart.md, content/reference/deploykf-values.md
=> docs: small updates

overrides/partials/header.html, overrides/partials/nav-item.html, overrides/partials/nav.html, overrides/partials/palette.html, requirements.txt
=> chore: fix back button instant navigation & fork mkdocs-material

content/about/architecture.md, content/about/introduction.md, content/about/kubeflow-vs-deploykf.md, content/assets/stylesheets/overrides.css, content/guides/kubeflow-distributions.md, macros/custom_macros.py
=> docs: add star-history chart

content/about/introduction.md, content/assets/stylesheets/home.css, content/assets/stylesheets/overrides.css, content/guides/getting-started.md, content/guides/local-quickstart.md, mkdocs.yml, overrides/home.html
=> chore: add introduction video

content/about/community.md, content/about/introduction.md, content/about/kubeflow-vs-deploykf.md, content/assets/stylesheets/admonitions.css, content/assets/stylesheets/color.css, content/assets/stylesheets/home.css, content/assets/stylesheets/overrides.css, content/guides/getting-started.md, content/guides/kubeflow-distributions.md, content/guides/local-quickstart.md, overrides/home.html
=> docs: add "featured stories"

content/guides/local-quickstart.md
=> docs: local-quickstart.md fix k3s

content/assets/javascripts/feedback.js, mkdocs.yml, overrides/home.html
=> chore: fix cdn

content/assets/javascripts/feedback.js, mkdocs.yml
=> chore: fix datalayer

content/assets/javascripts/feedback.js
=> chore: fix ztag

content/guides/dependencies/istio.md, content/guides/getting-started.md
=> docs: update "modes of operation"

content/assets/stylesheets/admonitions.css, content/guides/dependencies/istio.md, content/releases/version-matrix--kubeflow-tools.csv, content/user-guides/access-kubeflow-pipelines-api.md, mkdocs.yml
=> docs: more updates for 0.1.4

content/guides/dependencies/argocd.md, content/guides/dependencies/istio.md
=> docs: update argocd page for `argocd.appNamePrefix`

content/guides/deploykf-cli.md, content/guides/platform/deploykf-gateway.md
There were small issue with ingress-nginx example.  
path /* is leads to location /*/  which is looks not valid. 
Updated location works fine.
=> docs: nginx ingress example

content/guides/platform/deploykf-gateway.md
=> docs: fix exposing gateway ingress examples

content/guides/getting-started.md, content/guides/kubeflow-distributions.md, content/guides/local-quickstart.md, overrides/home.html
=> docs: update getting started & home

content/about/community.md, content/about/introduction.md, content/about/support.md, content/faq.md, content/guides/dependencies/argocd.md, content/guides/dependencies/cert-manager.md, content/guides/dependencies/istio.md, content/guides/dependencies/kyverno.md, content/guides/getting-started.md, content/guides/local-quickstart.md, content/guides/platform/deploykf-gateway.md
=> docs: update many pages

content/about/community.md, content/about/introduction.md, content/assets/stylesheets/admonitions.css, content/faq.md, content/guides/.pages, content/guides/configs.md, content/guides/dependencies/argocd.md, content/guides/getting-started.md, content/guides/local-quickstart.md, content/guides/platform/deploykf-gateway.md, content/reference/deploykf-values.md, content/releases/changelog-deploykf-cli.md, content/releases/changelog-deploykf.md, dev/generate_changelog.py, update_changelogs.sh
=> docs: update content

content/guides/configs.md, content/guides/platform/.pages, content/guides/platform/deploykf-gateway.md, content/guides/platform/image-pull-secrets.md
=> docs: add image pull secrets guide

content/about/.pages, content/about/introduction.md, content/about/kubeflow-vs-deploykf.md, content/assets/stylesheets/color.css, content/assets/stylesheets/overrides.css, content/faq.md, content/guides/getting-started.md, content/guides/kubeflow-distributions.md, content/reference/future-tools.md, content/reference/tools.md, macros/custom_macros.py, mkdocs.yml, overrides/home.html
=> docs: update homepage and comparison

content/guides/platform/deploykf-authentication.md
=> docs: fix incorrect values for existing-secret `staticPasswords`

content/guides/getting-started.md, content/guides/local-quickstart.md, content/guides/values.md
=> docs: add warning about existing argo workflows

content/guides/local-quickstart.md
=> docs: add warning about sync order in quickstart

content/guides/platform/deploykf-authentication.md, content/guides/platform/deploykf-gateway.md, content/guides/platform/deploykf-profiles.md
=> docs: add hostname example to ingress templates

content/guides/external/object-store.md, content/guides/getting-started.md, content/guides/local-quickstart.md
=> docs: update object store key guide

content/guides/dependencies/argocd.md, content/guides/getting-started.md, content/guides/local-quickstart.md
=> docs: update app-of-apps example

content/assets/stylesheets/home.css, overrides/home.html, overrides/main.html
=> fix: homepage background jumping

content/guides/external/object-store.md
=> docs: make object store iam more clear

content/assets/stylesheets/color.css, content/guides/dependencies/argocd.md, content/guides/getting-started.md, content/guides/local-quickstart.md, content/guides/values.md
=> docs: update off-cluster argocd & getting started guides

content/about/introduction.md, content/assets/stylesheets/color.css, content/assets/stylesheets/home.css, content/guides/dependencies/argocd.md, content/guides/getting-started.md, content/guides/local-quickstart.md, overrides/404.html, overrides/home.html, overrides/main.html, overrides/partials/javascripts/base.html
=> docs: updates

content/guides/getting-started.md, content/guides/platform/deploykf-gateway.md, content/guides/uninstall.md, content/guides/upgrade.md, content/privacy-policy/website.md, content/reference/deploykf-values.md, content/releases/changelog-deploykf-cli.md, content/releases/changelog-deploykf.md, content/releases/full-changelog-deploykf-cli.md, content/releases/full-changelog-deploykf.md, content/releases/version-matrix.md, dev/generate_changelog.py, mkdocs.yml, update_changelogs.sh
=> docs: update search and https guides

content/guides/platform/deploykf-gateway.md
=> docs: explain how to use custom TLS cert

content/guides/platform/deploykf-gateway.md
=> docs: improve custom tls cert guide

content/guides/getting-started.md, content/guides/local-quickstart.md
=> docs: update argocd plugin with helm links

content/guides/dependencies/istio.md, content/guides/getting-started.md, content/guides/local-quickstart.md, content/guides/platform/deploykf-profiles.md
=> docs: update istio and profile guides

content/guides/external/object-store.md, content/guides/getting-started.md, content/guides/local-quickstart.md, content/guides/platform/deploykf-gateway.md, requirements.txt
=> docs: update local quickstart

content/guides/dependencies/istio.md, content/guides/external/object-store.md, content/guides/getting-started.md, content/guides/local-quickstart.md, content/guides/platform/image-pull-secrets.md
=> docs: collapse all steps by default & improve object store guide

content/guides/getting-started.md, content/releases/changelog-deploykf-cli.md, content/releases/changelog-deploykf.md, content/releases/full-changelog-deploykf-cli.md, content/releases/full-changelog-deploykf.md, content/releases/tool-versions--kubeflow-pipelines.csv, content/releases/tool-versions.md, content/releases/version-matrix.md, dev/generate_changelog.py, update_changelogs.sh
=> docs: update changelog structure

content/guides/configs.md, content/guides/dependencies/argocd.md, content/guides/getting-started.md, content/guides/local-quickstart.md, content/guides/platform/.pages, content/guides/platform/deploykf-gateway.md, content/guides/platform/image-pull-secrets.md, content/guides/platform/offline.md, content/guides/upgrade.md, content/releases/version-matrix--argocd.csv, content/releases/version-matrix--cert-manager.csv, content/releases/version-matrix--istio.csv, content/releases/version-matrix--kubernetes.csv, content/releases/version-matrix--kyverno.csv
=> docs: update image pull secrets & add air-gapped guide

content/guides/dependencies/cert-manager.md, content/guides/dependencies/istio.md, content/guides/platform/offline.md
=> docs: update istio & cert-manager guides

content/guides/getting-started.md, content/guides/local-quickstart.md, content/guides/platform/deploykf-gateway.md
=> docs: clarify the port-forward steps

content/guides/getting-started.md, content/guides/local-quickstart.md
=> docs: improve getting started

content/guides/getting-started.md, content/guides/platform/deploykf-gateway.md
=> docs: clarify LoadBalancer docs

content/about/support.md, content/guides/dependencies/argocd.md, content/guides/external/mysql.md, content/guides/getting-started.md, content/guides/local-quickstart.md, mkdocs.yml, requirements.txt
=> docs: add note about azure aks + update mkdocs to 1.6.0

content/guides/external/object-store.md
=> docs: fix aws s3 endpoint to explain regions

content/guides/platform/deploykf-authentication.md
=> docs: update auth guide

content/about/community.md, content/about/introduction.md, content/about/support.md
=> docs: update slack link

mkdocs.yml
=> ci: fix build

content/guides/tools/kubeflow-notebooks.md
=> docs: fix the notebook template override docs

content/guides/values.md
=> docs: improve the clarity of the values example

content/releases/tool-versions.md, content/user-guides/access-kubeflow-pipelines-api.md
=> docs: clarify which KFP SDK version to use

content/guides/dependencies/istio.md, content/guides/platform/deploykf-gateway.md
=> docs: add `alb.ingress.kubernetes.io/healthcheck-protocol` to example

content/guides/platform/deploykf-gateway.md
=> docs: add information about other nginx ingress controller

content/guides/getting-started.md, content/guides/troubleshooting.md
=> docs: add "Inotify Limits" to getting started requirements

content/user-guides/access-kubeflow-pipelines-api.md
This should only affect upstream Kubeflow, see https://github.com/kubeflow/manifests/issues/2844
=> docs: handle dex approval screen in `KFPClientManager`

content/guides/dependencies/argocd.md, content/guides/getting-started.md, content/guides/troubleshooting.md
=> docs: add linux requirements to getting started + istio linux modules

content/guides/tools/choose-tools.md, content/guides/tools/kubeflow-poddefaults.md
=> docs: add "enable or disable tools" guide

content/about/kubeflow-vs-deploykf.md, content/assets/stylesheets/overrides.css, macros/custom_macros.py
=> docs: improve kubeflow vs deployKF page

content/assets/stylesheets/home.css, content/assets/stylesheets/overrides.css, overrides/home.html, overrides/main.html
=> chore: update banner styles

overrides/main.html
=> chore: update enterprise banner

content/guides/dependencies/istio.md, content/guides/platform/deploykf-authentication.md
=> docs: update existing istio gateway guide
